//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pahkat {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Pahkat.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báhkat.
        /// </summary>
        public static string AppName {
            get {
                return ResourceManager.GetString("AppName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatically Send Crash Reports.
        /// </summary>
        public static string AutoCrashReporting {
            get {
                return ResourceManager.GetString("AutoCrashReporting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báhkat v{0} is now available. It is highly recommended that you update as soon as possible. Update now?.
        /// </summary>
        public static string BahkatUpdateBody {
            get {
                return ResourceManager.GetString("BahkatUpdateBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Báhkat Update Available.
        /// </summary>
        public static string BahkatUpdateTitle {
            get {
                return ResourceManager.GetString("BahkatUpdateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to cancel all downloads?.
        /// </summary>
        public static string CancelDownloadsBody {
            get {
                return ResourceManager.GetString("CancelDownloadsBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel Downloads.
        /// </summary>
        public static string CancelDownloadsTitle {
            get {
                return ResourceManager.GetString("CancelDownloadsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check For Updates....
        /// </summary>
        public static string CheckForUpdates {
            get {
                return ResourceManager.GetString("CheckForUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to send a crash report to the developers? No personal or private information is sent. (Recommended).
        /// </summary>
        public static string CrashReportBody {
            get {
                return ResourceManager.GetString("CrashReportBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Crash Report.
        /// </summary>
        public static string CrashReportTitle {
            get {
                return ResourceManager.GetString("CrashReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Daily.
        /// </summary>
        public static string Daily {
            get {
                return ResourceManager.GetString("Daily", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloaded.
        /// </summary>
        public static string Downloaded {
            get {
                return ResourceManager.GetString("Downloaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error 😞.
        /// </summary>
        public static string DownloadError {
            get {
                return ResourceManager.GetString("DownloadError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading....
        /// </summary>
        public static string Downloading {
            get {
                return ResourceManager.GetString("Downloading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Invalid Version.
        /// </summary>
        public static string ErrorInvalidVersion {
            get {
                return ResourceManager.GetString("ErrorInvalidVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: No Installer.
        /// </summary>
        public static string ErrorNoInstaller {
            get {
                return ResourceManager.GetString("ErrorNoInstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unknown Item.
        /// </summary>
        public static string ErrorUnknownPackage {
            get {
                return ResourceManager.GetString("ErrorUnknownPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 4 Weeks.
        /// </summary>
        public static string EveryFourWeeks {
            get {
                return ResourceManager.GetString("EveryFourWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Every 2 Weeks.
        /// </summary>
        public static string EveryTwoWeeks {
            get {
                return ResourceManager.GetString("EveryTwoWeeks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finish.
        /// </summary>
        public static string Finish {
            get {
                return ResourceManager.GetString("Finish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string Install {
            get {
                return ResourceManager.GetString("Install", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installed.
        /// </summary>
        public static string Installed {
            get {
                return ResourceManager.GetString("Installed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installing {0} {1}....
        /// </summary>
        public static string InstallingPackage {
            get {
                return ResourceManager.GetString("InstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface Language.
        /// </summary>
        public static string InterfaceLanguage {
            get {
                return ResourceManager.GetString("InterfaceLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        public static string Never {
            get {
                return ResourceManager.GetString("Never", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next update check at: {0}.
        /// </summary>
        public static string NextUpdateDue {
            get {
                return ResourceManager.GetString("NextUpdateDue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} items remaining..
        /// </summary>
        public static string NItemsRemaining {
            get {
                return ResourceManager.GetString("NItemsRemaining", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Items Selected.
        /// </summary>
        public static string NoPackagesSelected {
            get {
                return ResourceManager.GetString("NoPackagesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to --.
        /// </summary>
        public static string NotApplicable {
            get {
                return ResourceManager.GetString("NotApplicable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Installed.
        /// </summary>
        public static string NotInstalled {
            get {
                return ResourceManager.GetString("NotInstalled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No new updates were found..
        /// </summary>
        public static string NoUpdatesBody {
            get {
                return ResourceManager.GetString("NoUpdatesBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Updates.
        /// </summary>
        public static string NoUpdatesTitle {
            get {
                return ResourceManager.GetString("NoUpdatesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Updates Available.
        /// </summary>
        public static string NUpdatesAvailable {
            get {
                return ResourceManager.GetString("NUpdatesAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string Ok {
            get {
                return ResourceManager.GetString("Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Package Manager.
        /// </summary>
        public static string OpenPackageManager {
            get {
                return ResourceManager.GetString("OpenPackageManager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You may now close this window, or return to the main screen..
        /// </summary>
        public static string ProcessCompletedBody {
            get {
                return ResourceManager.GetString("ProcessCompletedBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done!.
        /// </summary>
        public static string ProcessCompletedTitle {
            get {
                return ResourceManager.GetString("ProcessCompletedTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process {0} Items.
        /// </summary>
        public static string ProcessNPackages {
            get {
                return ResourceManager.GetString("ProcessNPackages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remind Me Later.
        /// </summary>
        public static string RemindMeLater {
            get {
                return ResourceManager.GetString("RemindMeLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository.
        /// </summary>
        public static string Repository {
            get {
                return ResourceManager.GetString("Repository", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repository Error.
        /// </summary>
        public static string RepositoryError {
            get {
                return ResourceManager.GetString("RepositoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an error while opening the repository:
        ///
        ///{0}.
        /// </summary>
        public static string RepositoryErrorBody {
            get {
                return ResourceManager.GetString("RepositoryErrorBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Later.
        /// </summary>
        public static string RestartLater {
            get {
                return ResourceManager.GetString("RestartLater", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Now.
        /// </summary>
        public static string RestartNow {
            get {
                return ResourceManager.GetString("RestartNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is highly recommended that you restart your computer in order for some changes to take effect..
        /// </summary>
        public static string RestartRequiredBody {
            get {
                return ResourceManager.GetString("RestartRequiredBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time to reboot!.
        /// </summary>
        public static string RestartRequiredTitle {
            get {
                return ResourceManager.GetString("RestartRequiredTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Skip These Updates.
        /// </summary>
        public static string SkipTheseUpdates {
            get {
                return ResourceManager.GetString("SkipTheseUpdates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting....
        /// </summary>
        public static string Starting {
            get {
                return ResourceManager.GetString("Starting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstall.
        /// </summary>
        public static string Uninstall {
            get {
                return ResourceManager.GetString("Uninstall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uninstalling {0} {1}....
        /// </summary>
        public static string UninstallingPackage {
            get {
                return ResourceManager.GetString("UninstallingPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Available.
        /// </summary>
        public static string UpdateAvailable {
            get {
                return ResourceManager.GetString("UpdateAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Channel.
        /// </summary>
        public static string UpdateChannel {
            get {
                return ResourceManager.GetString("UpdateChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Frequency.
        /// </summary>
        public static string UpdateFrequency {
            get {
                return ResourceManager.GetString("UpdateFrequency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version Skipped.
        /// </summary>
        public static string VersionSkipped {
            get {
                return ResourceManager.GetString("VersionSkipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waiting for process to finish....
        /// </summary>
        public static string WaitingForCompletion {
            get {
                return ResourceManager.GetString("WaitingForCompletion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weekly.
        /// </summary>
        public static string Weekly {
            get {
                return ResourceManager.GetString("Weekly", resourceCulture);
            }
        }
    }
}
